# Generated by Django 6.1.1 on 2026-09-10 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0011_preferencia_color_logs'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialReporteIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_usuario', models.TextField()),
                ('sql_generado', models.TextField()),
                ('datos_json', models.JSONField(help_text='Snapshot: {columnas: [...], datos: [...]}')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='reportes_ia', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Historial reporte IA',
                'verbose_name_plural': 'Historial reportes IA',
                'db_table': 'historial_reporte_ia',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
