# Generated by Django 5.2.17 on 2026-09-07 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_sesion_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='CantonExistente',
            fields=[
                ('id_canton', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'canton_distrito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubzonaExistente',
            fields=[
                ('id_subzona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'subzona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZonaExistente',
            fields=[
                ('id_zona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'zona_planificacion',
                'managed': False,
            },
        ),
    ]
