# Generated by Django 5.2.17 on 2026-09-09 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_usuario_foto_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciaUsuario',
            fields=[
                ('id_preferencia', models.AutoField(primary_key=True, serialize=False)),
                ('color_sidebar', models.CharField(default='#111827', max_length=20)),
                ('color_graficos', models.CharField(default='#00AA5D', max_length=20)),
                ('logo_personalizado', models.ImageField(blank=True, max_length=255, null=True, upload_to='logos_usuarios/')),
                ('filas_por_pagina', models.PositiveSmallIntegerField(default=10)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Preferencia de usuario',
                'verbose_name_plural': 'Preferencias de usuario',
                'db_table': 'preferencia_usuario',
            },
        ),
    ]
