# Generated by Django 5.2.17 on 2026-09-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_preferencia_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferenciausuario',
            name='color_sidebar',
            field=models.CharField(default='#000000', max_length=20),
        ),
    ]
