# Generated by Django 5.2.17 on 2026-09-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_preferencia_sidebar_negro'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferenciausuario',
            name='color_logs',
            field=models.CharField(default='#00AA5D', max_length=20),
        ),
    ]
