# Generated by Django 5.1.15 on 2026-09-06 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subzona',
            fields=[
                ('id_nombre', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Subzona',
                'verbose_name_plural': 'Subzonas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ZonaPlanificacion',
            fields=[
                ('id_nombre', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('codigo', models.PositiveSmallIntegerField(unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Zona de planificación',
                'verbose_name_plural': 'Zonas de planificación',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CantonDistrito',
            fields=[
                ('id_nombre', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('subzona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cantones', to='geografia.subzona')),
            ],
            options={
                'verbose_name': 'Cantón / Distrito',
                'verbose_name_plural': 'Cantones / Distritos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_nombre', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=32)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_apertura', models.DateField(blank=True, null=True)),
                ('canton', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sucursales', to='geografia.cantondistrito')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='subzona',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subzonas', to='geografia.zonaplanificacion'),
        ),
    ]
