# Generated by Django 5.2.17 on 2026-09-06 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geografia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='fecha_cierre',
            field=models.DateField(blank=True, null=True),
        ),
    ]
