# Generated by Django 5.2.17 on 2026-09-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(blank=True, max_length=13, null=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'ordering': ['apellidos', 'nombres'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id_metodo_pago', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Método de pago',
                'verbose_name_plural': 'Métodos de pago',
                'db_table': 'metodo_pago',
                'ordering': ['id_metodo_pago'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PagoVenta',
            fields=[
                ('pk', models.CompositePrimaryKey('venta', 'metodo_pago', blank=True, editable=False, primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Pago de venta',
                'verbose_name_plural': 'Pagos de venta',
                'db_table': 'pago_venta',
                'ordering': ['metodo_pago__nombre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TerminalPOS',
            fields=[
                ('id_terminal', models.AutoField(primary_key=True, serialize=False)),
                ('numero_serie', models.CharField(max_length=50)),
                ('estado_activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Terminal POS',
                'verbose_name_plural': 'Terminales POS',
                'db_table': 'terminal_pos',
                'ordering': ['id_terminal'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TurnoCaja',
            fields=[
                ('id_turno', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('monto_apertura', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_cierre_declarado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Turno de caja',
                'verbose_name_plural': 'Turnos de caja',
                'db_table': 'turno_caja',
                'ordering': ['-fecha_apertura', '-id_turno'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'venta',
                'ordering': ['-fecha_hora', '-id_venta'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VentaDetalle',
            fields=[
                ('pk', models.CompositePrimaryKey('venta', 'producto', blank=True, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario_historico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_unitario_historico', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Detalle de venta',
                'verbose_name_plural': 'Detalles de venta',
                'db_table': 'venta_detalle',
                'ordering': ['producto__nombre'],
                'managed': False,
            },
        ),
    ]
