# Generated by Django 5.2.17 on 2026-09-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categoria',
                'ordering': ['nombre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventarioStock',
            fields=[
                ('pk', models.CompositePrimaryKey('sucursal', 'producto', blank=True, editable=False, primary_key=True, serialize=False)),
                ('cantidad_actual', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=5)),
            ],
            options={
                'verbose_name': 'Stock por sucursal',
                'verbose_name_plural': 'Stock por sucursal',
                'db_table': 'inventario_stock',
                'ordering': ['producto__nombre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoteCaducidad',
            fields=[
                ('id_lote', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_lote', models.CharField(max_length=50)),
                ('fecha_vencimiento', models.DateField()),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'db_table': 'lote_caducidad',
                'ordering': ['fecha_vencimiento'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_actual', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'ordering': ['nombre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroMerma',
            fields=[
                ('id_merma', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('motivo', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Merma',
                'verbose_name_plural': 'Mermas',
                'db_table': 'registro_merma',
                'ordering': ['-fecha'],
                'managed': False,
            },
        ),
    ]
