# Generated by Django 5.2.17 on 2026-09-07 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('usuarios', '0005_cantonexistente_subzonaexistente_zonaexistente'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialMovimiento',
            fields=[
                ('id_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('ENTRADA_LOTE', 'Entrada por lote'), ('VENTA_POS', 'Venta en POS'), ('MERMA', 'Baja por merma'), ('AJUSTE', 'Ajuste manual')], max_length=20)),
                ('cantidad', models.IntegerField(help_text='Positivo si entra, negativo si sale.')),
                ('stock_resultante', models.IntegerField()),
                ('referencia', models.CharField(blank=True, max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.producto')),
                ('sucursal', models.ForeignKey(db_column='id_sucursal', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='usuarios.sucursalexistente')),
                ('usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Movimiento de inventario',
                'verbose_name_plural': 'Movimientos de inventario',
                'db_table': 'historial_movimiento',
                'ordering': ['-fecha', '-id_movimiento'],
                'indexes': [models.Index(fields=['producto', 'sucursal', '-fecha'], name='idx_kardex_producto')],
            },
        ),
    ]
